	package com.example.cricEcom.entities;

	import java.math.BigDecimal;
	import java.time.LocalDateTime;
	import java.util.List;

	import jakarta.persistence.Column;
	import jakarta.persistence.Entity;
	import jakarta.persistence.EnumType;
	import jakarta.persistence.Enumerated;
	import jakarta.persistence.GeneratedValue;
	import jakarta.persistence.GenerationType;
	import jakarta.persistence.Id;
	import jakarta.persistence.ManyToOne;
	import jakarta.persistence.PrePersist;
	import jakarta.persistence.PreUpdate;
	import lombok.AllArgsConstructor;
	import lombok.Builder;
	import lombok.Data;
	import lombok.NoArgsConstructor;

	@NoArgsConstructor
	@AllArgsConstructor
	@Data
	@Entity
	@Builder

	public class Payment {

			@Id
			@GeneratedValue(strategy = GenerationType.IDENTITY)
			private Long id;

			@ManyToOne(optional = false)
			private User user;

			@ManyToOne(optional = false)
			private Orders order;
			// Amount to be paid (always set by backend)
			@Column(nullable = false, precision = 12, scale = 2)
			private BigDecimal amount;



			// ID generated by Razorpay/Stripe
			@Column(nullable = false, unique = true)
			private String gatewayOrderId;

			// ID returned after successful payment
			private String gatewayPaymentId;



			@Enumerated(EnumType.STRING)
			@Column(nullable = false)
			private PaymentStatus status;      // PENDING or SUCCESS

			@Column(nullable = false, updatable = false)
			private LocalDateTime createdAt;

			@Column(nullable = false)
			private LocalDateTime updatedAt;

			// Auto-set timestamps
			@PrePersist
			protected void onCreate() {
				this.createdAt = LocalDateTime.now();
				this.updatedAt = LocalDateTime.now();
			}

			@PreUpdate

			protected void onUpdate() {
				this.updatedAt = LocalDateTime.now();
			}

			public enum PaymentStatus {
				PENDING,
				SUCCESS,

				FAILED
			}
		}



